### ISSUE TITLE
Al met al …

### ISSUE THREAD

**Issue by vasilisvg** [larsdouweschuitema/minor-css-to-the-rescue#13]
Je hebt nog niet zo veel. Laat eens wat meer zien!
Kijk eens of je hier een *echte* site van kan maken. Lukt het je om alle elementen op een logische manier te tonen? Het mag op één pagina, maar ook op meerdere pagina's. Het onderwerp mag je natuurlijk zelf weten.

**Comment by larsdouweschuitema** [comment]
Created a site using the components and separated them on different pages to get a better feeling of how it would be on a real site.
