### ISSUE TITLE
Navigatie

### ISSUE THREAD

**Issue by vasilisvg** [larsdouweschuitema/minor-css-to-the-rescue#2]
Ziet er netjes uit! 

- Breakpoint kan misschien iets eerder, blijft nu wel erg lang een hamburger
- Geen :focus styles op de menu-items
- Submenu ontoegankelijk als ik tab met mijn toetsenbord
- Geen onderscheid tussen gewoon menu-item en het item waar een submenu onder zit.

**Comment by larsdouweschuitema** [comment]
Thanks for the feedback.

- Changed breakpoint from 48em to 36em
- Added :focus to menu-items
- Added accessibility to submenu using tab
- Added arrow icon to top level menu-items with a sub menu

Added functionality to check for a focus / blur on top level menu-items that contain a sub menu, and open / close them when the user is pressing tab on one of these items. Will rework the bottom code later.

JavaScript:
```javascript
    childrenOnFocus() {
      menu.list.links.forEach(link => {
        link.addEventListener('focus', function(e) {
          if(link.parentElement.children.length > 1) {
            if(link.classList.contains("has-children")) {
              link.parentElement.getElementsByTagName('ul')[0].style.display = "flex";
              link.parentElement.getElementsByTagName('ul')[0].style.opacity = 1;
            }
          }
        }, true);
      });
    },

    childrenOnBlur() {
      menu.list.links.forEach(link => {
        link.addEventListener('blur', function(e) {
          if(link.parentElement.children.length > 1) {
            if(link.classList.contains("has-children")) {
              link.parentElement.getElementsByTagName('ul')[0].style.display = "none";
              link.parentElement.getElementsByTagName('ul')[0].style.opacity = 0;
            }
          }
        }, true);
      });
    },
```
